In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('Energy_consumption_dataset.csv')
df

,Month,Hour,DayOfWeek,Holiday,Temperature,Humidity,SquareFootage,Occupancy,HVACUsage,LightingUsage,RenewableEnergy,EnergyConsumption
0,1,0,Saturday,No,25.139433,43.431581,1565.693999,5,On,Off,2.774699,75.364373
1,1,1,Saturday,No,27.731651,54.225919,1411.064918,1,On,On,21.831384,83.401855
2,1,2,Saturday,No,28.704277,58.907658,1755.715009,2,Off,Off,6.764672,78.270888
3,1,3,Saturday,No,20.080469,50.371637,1452.316318,1,Off,On,8.623447,56.519850
4,1,4,Saturday,No,23.097359,51.401421,1094.130359,9,On,Off,3.071969,70.811732
...,...,...,...,...,...,...,...,...,...,...,...,...
4995,12,6,Sunday,Yes,26.338718,52.580000,1563.567259,7,On,On,20.591717,70.270344
4996,12,17,Monday,No,20.007565,42.765607,1999.982252,5,Off,On,7.536319,73.943071
4997,12,13,Thursday,Yes,26.226253,30.015975,1999.982252,5,Off,On,28.162193,85.784613
4998,12,8,Saturday,Yes,24.673206,50.223939,1240.811298,2,On,On,20.918483,63.784001
4999,12,1,Saturday,Yes,25.802872,41.798829,1793.658686,6,Off,Off,8.334079,53.263278

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Month              5000 non-null   int64
 1   Hour               5000 non-null   int64
 2   DayOfWeek          5000 non-null   str
 3   Holiday            5000 non-null   str
 4   Temperature        5000 non-null   float64
 5   Humidity           5000 non-null   float64
 6   SquareFootage      5000 non-null   float64
 7   Occupancy          5000 non-null   int64
 8   HVACUsage          5000 non-null   str
 9   LightingUsage      5000 non-null   str
 10  RenewableEnergy    5000 non-null   float64
 11  EnergyConsumption  5000 non-null   float64
dtypes: float64(5), int64(3), str(4)
memory usage: 468.9 KB

In [4]:
df.memory_usage(deep=True)

Index                   132
Month                 40000
Hour                  40000
DayOfWeek            280734
Holiday              257344
Temperature           40000
Humidity              40000
SquareFootage         40000
Occupancy             40000
HVACUsage            257500
LightingUsage        257543
RenewableEnergy       40000
EnergyConsumption     40000
dtype: int64

In [5]:
df['DayOfWeek'].unique()

<StringArray>
['Saturday', 'Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday']
Length: 7, dtype: str

In [6]:
df['DayOfWeek'] = df['DayOfWeek'].map({'Monday': 1, 'Tuesday': 2, 'Wednesday': 3, 'Thursday': 4, 'Friday': 5, 'Saturday': 6, 'Sunday': 7}).astype('category')

In [7]:
df.memory_usage(deep=True)

Index                   132
Month                 40000
Hour                  40000
DayOfWeek              5056
Holiday              257344
Temperature           40000
Humidity              40000
SquareFootage         40000
Occupancy             40000
HVACUsage            257500
LightingUsage        257543
RenewableEnergy       40000
EnergyConsumption     40000
dtype: int64

In [8]:
df['Holiday'].unique()

<StringArray>
['No', 'Yes']
Length: 2, dtype: str

In [9]:
df['Holiday'] = df['Holiday'].map({'No': 0, 'Yes': 1}).astype('category')

In [10]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Month              5000 non-null   int64
 1   Hour               5000 non-null   int64
 2   DayOfWeek          5000 non-null   category
 3   Holiday            5000 non-null   category
 4   Temperature        5000 non-null   float64
 5   Humidity           5000 non-null   float64
 6   SquareFootage      5000 non-null   float64
 7   Occupancy          5000 non-null   int64
 8   HVACUsage          5000 non-null   str
 9   LightingUsage      5000 non-null   str
 10  RenewableEnergy    5000 non-null   float64
 11  EnergyConsumption  5000 non-null   float64
dtypes: category(2), float64(5), int64(3), str(2)
memory usage: 400.6 KB

In [11]:
df.memory_usage(deep=True)

Index                   132
Month                 40000
Hour                  40000
DayOfWeek              5056
Holiday                5016
Temperature           40000
Humidity              40000
SquareFootage         40000
Occupancy             40000
HVACUsage            257500
LightingUsage        257543
RenewableEnergy       40000
EnergyConsumption     40000
dtype: int64

In [12]:
df['HVACUsage'].unique()

<StringArray>
['On', 'Off']
Length: 2, dtype: str

In [13]:
df['HVACUsage'] = df['HVACUsage'].map({'On': 1, 'Off': 0}).astype('category')

In [14]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Month              5000 non-null   int64
 1   Hour               5000 non-null   int64
 2   DayOfWeek          5000 non-null   category
 3   Holiday            5000 non-null   category
 4   Temperature        5000 non-null   float64
 5   Humidity           5000 non-null   float64
 6   SquareFootage      5000 non-null   float64
 7   Occupancy          5000 non-null   int64
 8   HVACUsage          5000 non-null   category
 9   LightingUsage      5000 non-null   str
 10  RenewableEnergy    5000 non-null   float64
 11  EnergyConsumption  5000 non-null   float64
dtypes: category(3), float64(5), int64(3), str(1)
memory usage: 366.4 KB

In [15]:
df['HVACUsage'].unique()

[1, 0]
Categories (2, int64): [0, 1]

In [16]:
df.memory_usage(deep=True)

Index                   132
Month                 40000
Hour                  40000
DayOfWeek              5056
Holiday                5016
Temperature           40000
Humidity              40000
SquareFootage         40000
Occupancy             40000
HVACUsage              5016
LightingUsage        257543
RenewableEnergy       40000
EnergyConsumption     40000
dtype: int64

In [17]:
df['LightingUsage'].unique()

<StringArray>
['Off', 'On']
Length: 2, dtype: str

In [18]:
df['LightingUsage'] = df['LightingUsage'].map({'On': 1, 'Off': 0}).astype('category')

In [19]:
df['HVACUsage'].unique()

[1, 0]
Categories (2, int64): [0, 1]

In [20]:
df.memory_usage(deep=True)

Index                  132
Month                40000
Hour                 40000
DayOfWeek             5056
Holiday               5016
Temperature          40000
Humidity             40000
SquareFootage        40000
Occupancy            40000
HVACUsage             5016
LightingUsage         5016
RenewableEnergy      40000
EnergyConsumption    40000
dtype: int64

In [21]:
df

,Month,Hour,DayOfWeek,Holiday,Temperature,Humidity,SquareFootage,Occupancy,HVACUsage,LightingUsage,RenewableEnergy,EnergyConsumption
0,1,0,6,0,25.139433,43.431581,1565.693999,5,1,0,2.774699,75.364373
1,1,1,6,0,27.731651,54.225919,1411.064918,1,1,1,21.831384,83.401855
2,1,2,6,0,28.704277,58.907658,1755.715009,2,0,0,6.764672,78.270888
3,1,3,6,0,20.080469,50.371637,1452.316318,1,0,1,8.623447,56.519850
4,1,4,6,0,23.097359,51.401421,1094.130359,9,1,0,3.071969,70.811732
...,...,...,...,...,...,...,...,...,...,...,...,...
4995,12,6,7,1,26.338718,52.580000,1563.567259,7,1,1,20.591717,70.270344
4996,12,17,1,0,20.007565,42.765607,1999.982252,5,0,1,7.536319,73.943071
4997,12,13,4,1,26.226253,30.015975,1999.982252,5,0,1,28.162193,85.784613
4998,12,8,6,1,24.673206,50.223939,1240.811298,2,1,1,20.918483,63.784001
4999,12,1,6,1,25.802872,41.798829,1793.658686,6,0,0,8.334079,53.263278

In [22]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Month              5000 non-null   int64
 1   Hour               5000 non-null   int64
 2   DayOfWeek          5000 non-null   category
 3   Holiday            5000 non-null   category
 4   Temperature        5000 non-null   float64
 5   Humidity           5000 non-null   float64
 6   SquareFootage      5000 non-null   float64
 7   Occupancy          5000 non-null   int64
 8   HVACUsage          5000 non-null   category
 9   LightingUsage      5000 non-null   category
 10  RenewableEnergy    5000 non-null   float64
 11  EnergyConsumption  5000 non-null   float64
dtypes: category(4), float64(5), int64(3)
memory usage: 332.3 KB

In [23]:
df['Month'] = df['Month'].astype('int8')
df['Hour'] = df['Hour'].astype('int8')
df['Occupancy'] = df['Occupancy'].astype('int8')

In [24]:
df.memory_usage(deep=True)

Index                  132
Month                 5000
Hour                  5000
DayOfWeek             5056
Holiday               5016
Temperature          40000
Humidity             40000
SquareFootage        40000
Occupancy             5000
HVACUsage             5016
LightingUsage         5016
RenewableEnergy      40000
EnergyConsumption    40000
dtype: int64

In [25]:
df['Temperature'] = df['Temperature'].astype('float32')
df['Humidity'] = df['Humidity'].astype('float32')
df['SquareFootage'] = df['SquareFootage'].astype('float32')
df['RenewableEnergy'] = df['RenewableEnergy'].astype('float32')
df['EnergyConsumption'] = df['EnergyConsumption'].astype('float32')

In [26]:
df.memory_usage(deep=True)

Index                  132
Month                 5000
Hour                  5000
DayOfWeek             5056
Holiday               5016
Temperature          20000
Humidity             20000
SquareFootage        20000
Occupancy             5000
HVACUsage             5016
LightingUsage         5016
RenewableEnergy      20000
EnergyConsumption    20000
dtype: int64

In [27]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Month              5000 non-null   int8
 1   Hour               5000 non-null   int8
 2   DayOfWeek          5000 non-null   category
 3   Holiday            5000 non-null   category
 4   Temperature        5000 non-null   float32
 5   Humidity           5000 non-null   float32
 6   SquareFootage      5000 non-null   float32
 7   Occupancy          5000 non-null   int8
 8   HVACUsage          5000 non-null   category
 9   LightingUsage      5000 non-null   category
 10  RenewableEnergy    5000 non-null   float32
 11  EnergyConsumption  5000 non-null   float32
dtypes: category(4), float32(5), int8(3)
memory usage: 132.1 KB

In [28]:
df.describe()

,Month,Hour,Temperature,Humidity,SquareFootage,Occupancy,RenewableEnergy,EnergyConsumption
count,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000
mean,6.251200,11.556000,24.946823,45.478146,1507.403198,4.576000,15.201196,76.794922
std,3.588687,6.888306,3.041677,8.972691,293.147217,2.906185,9.157038,9.231573
min,1.000000,0.000000,20.007565,30.015974,1000.512634,0.000000,0.006642,53.263279
25%,3.000000,6.000000,22.453790,38.111105,1253.906616,2.000000,7.477928,70.419584
50%,6.000000,11.000000,24.831846,45.793123,1513.581116,5.000000,15.343831,76.696266
75%,9.000000,18.000000,27.427281,52.696651,1754.846436,7.000000,22.889997,83.246275
max,12.000000,23.000000,29.998671,59.969086,1999.982300,9.000000,29.965328,99.201118

In [29]:
df.to_csv('Energy_consumption_dataset_final.csv', index=False)

In [30]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Month              5000 non-null   int8
 1   Hour               5000 non-null   int8
 2   DayOfWeek          5000 non-null   category
 3   Holiday            5000 non-null   category
 4   Temperature        5000 non-null   float32
 5   Humidity           5000 non-null   float32
 6   SquareFootage      5000 non-null   float32
 7   Occupancy          5000 non-null   int8
 8   HVACUsage          5000 non-null   category
 9   LightingUsage      5000 non-null   category
 10  RenewableEnergy    5000 non-null   float32
 11  EnergyConsumption  5000 non-null   float32
dtypes: category(4), float32(5), int8(3)
memory usage: 132.1 KB